### ISSUE TITLE
Add a paragraph break in Homepage header text

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/frontline-stories#139]
The Frontline Stories project uplifts and spotlights the human element at the heart of the coronavirus pandemic. It puts everyday individuals most directly impacted by the crisis—medical staff, essential workers, the economically displaced, patients and their families—at the forefront of the conversation.

In sharing our stories, we are giving voice to the need for a people-centered response. We are joining together to demand and mobilize for change that serves us, the people at the front lines.

**Comment by nathanmwilliams** [comment]
Plus make second paragraph BOLD but first one not bold.

**Comment by nathanmwilliams** [comment]
Plus slight copy edit (included in first Comment).

**Comment by meganrm** [comment]
@nathanmwilliams  you should be able to edit the copy here, i'll work on the text break and styling

**Comment by nathanmwilliams** [comment]
Ah yeah, sorry for forgetting that!
