### ISSUE TITLE
Add Partner icons to footer

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/frontline-stories#190]
"Partners"

Transparent. PVWC Logo.png
cpda-logo.png
embarc_white.png
nywsa-logo.png
thp_logo_vertical.png
Six Stacked Logo.png
GPAS Logo Black Web (1).png
TagLogo_Ctr_Blue60Blk.png
AFSCME Logo Only 2C_color.png
NAACP_Sig_Y&C.png
4b-2 (2).png
black-redlogo-11.png
OFW-Logo (1).png
be-a-hero-logo.png
CD-Logo-Navy.png

**Comment by nathanmwilliams** [comment]
And separately add:

"For more COVID stories visit Be A hero's stories website."

And then display logo: Be A Hero logo.png

**Comment by meganrm** [comment]
do we want to link to 'be a hero stories'?

**Comment by nathanmwilliams** [comment]
Yeah. This link: https://shareyourcovidstory.com/
