### ISSUE TITLE
Remove top navigation buttons

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/frontline-stories#38]
![top nav](https://user-images.githubusercontent.com/25805849/81513697-2a1b0e80-92df-11ea-8df9-40469a9b03e4.png)

**Comment by meganrm** [comment]
I removed form examples.do you not want an about page or a contact form?

**Comment by nathanmwilliams** [comment]
I don't think we need a contact form outside of the email listed on About plus the Submit a Story form.

I think About page is good but fine just being on the bottom of the page.
