### ISSUE TITLE
Make "Name" field optional

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/frontline-stories#57]
Per Hub request: "If a storyteller doesn’t have their name listed, leave the name portion blank (i.e. if the Name field in the master sheet just says “families of victims”"

**Comment by meganrm** [comment]
I'm using the name + date as a unique id. I'm going to add a "display name: true/false" to the form. That way if it is something like 'families of victims" i'll still use that to make a unique id, but it wont show up on the card

**Comment by nathanmwilliams** [comment]
Cool. Not critical for tomorrow but they have some stories with multiple names we should figure out how best to display.
