### ISSUE TITLE
Bring Top Nav back (sorry!)

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/frontline-stories#62]
Per Hub's request.

Top nav for desktop ("hamburger" for mobile):

About
Submit a Story
[Subscribe](https://thehubproject.us19.list-manage.com/subscribe?u=71c118e79d1b482e43272a116&id=e3236c52d5)
Share: FB, twitter

**Comment by meganrm** [comment]
need to add share buttons still
